# Kartenfärbung

In [6]:
import numpy as np

a = [[0, 1, 1, 0, 1, 0], 
     [1, 0, 1, 1, 1, 0],
     [1, 1, 0, 1, 0, 0],
     [0, 1, 1, 0, 0, 1],
     [1, 1, 0, 0, 0, 0],
     [0, 0, 0, 1, 0 ,0]]

a = np.array(a)

def greedycoloring(a:list[list[int]]):
  # Setze die Farbe des ersten Land (oben links in Array, auf erste Farbe)
  n = len(a)
  colorlist = [0]
  print(n)
  
  for i in range(1, n):
    curr_coll = 0
    for j in range(0, i + 1):
      # Basisfall, Land erreicht, Farbe setzen
      if j == i:
        colorlist.append(curr_coll)
      
      # Grenze zu Land j?
      if a[i][j] == 1:
        # Land j gleiche Farbe wie aktuelle Farbe?
        if colorlist[j] == curr_coll:
          curr_coll += 1
  
  return colorlist

print(a)
collist = greedycoloring(a)
print(collist)

[[0 1 1 0 1 0]
 [1 0 1 1 1 0]
 [1 1 0 1 0 0]
 [0 1 1 0 0 1]
 [1 1 0 0 0 0]
 [0 0 0 1 0 0]]
6
[0, 1, 2, 0, 2, 1]
