# 0-1 Rucksackproblem

Der folgende Code implementiert das fraktionale Rucksackproblem als dynamisches Programm.

In [2]:
class Value:
  def __init__(self, gewicht, wert):
    self.gewicht = gewicht
    self.wert = wert
  
  def __str__(self):
    return f"Value: {self.gewicht}kg / {self.wert}€"
  
  def __lt__(self, other):
    if not isinstance(other, Value):
      return NotImplemented
    return (self.wert / self.gewicht) < (other.wert / other.gewicht)
  
  def __gt__(self, other):
        if not isinstance(other, Value):
            return NotImplemented
        return (self.wert / self.gewicht) > (other.wert / other.gewicht)

class Rucksack:
  def __init__(self, kapazität):
    self.kapazität = kapazität
    self.values = []
  
  def __str__(self):
    retval = f"Rucksack Kapazität: {self.kapazität}kg\n"
    for val in self.values:
      retval += str(val) + "\n"
    return retval

In [7]:
import numpy as np
def frakBag(values:list[Value], bag:Rucksack):

  n = len(values)
  m = bag.kapazität
  P = np.zeros((n + 1, m + 1))
  print(P)
  
  i = 1
  while i <= n:
    x = 1
    while x <= m:
      # Lese den Wert des vorherigen Element
      pref_value = P[i - 1][x]

      ## Prüfe ob der Wert im Rucksack wächst, wenn das vorherige Element entfernt wird und das aktuelle Eingepackt
      # Ermittle Wert und Gewicht des vorherigen Element
      wi = values[i-1].wert
      gi = values[i-1].gewicht
      if x - gi >= 0:
        tmp = P[i - 1][x - gi]
        pref_value_2 = wi + tmp
        P[i][x] = max(pref_value, pref_value_2)
      # Prüfe das maximum (welches Element passt besser)
      x += 1
    i += 1

  parts = []
  i -= 1
  x -= 1
  while i >= 0:
    curr = P[i][x]
    pref = P[i - 1][x]
    if pref < curr:
      # Nehme aktuelles Objekt mit
      gi = values[i-1].gewicht
      wi = values[i-1].wert
      bag.values.append(Value(gi, wi))
      bag.kapazität -= gi
      x = x - gi
    i -= 1

  
  return P

v1 = Value(1, 2)
v2 = Value(2, 3)
v3 = Value(3, 1)
v4 = Value(1, 1)
values = [v1, v2, v3, v4]

G = Rucksack(5)

P = frakBag(values, G)
print(P)
print(G)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2.]
 [0. 0. 3. 5. 5. 5.]
 [0. 0. 0. 5. 5. 5.]
 [0. 1. 1. 5. 6. 6.]]
Rucksack Kapazität: 1kg
Value: 1kg / 1€
Value: 2kg / 3€
Value: 1kg / 2€

