# Binomialkoeffizienten

Die Formel für den Binomialkoeffizienten ist:

$$
\binom{n}{k} = \frac{n!}{k!(n-k)!}
$$

Diese lässt sich auf die folgende Rekursionsformel umstellen:

$$
\binom{n}{k} = \binom{n-1}{k} + \binom{n-1}{k-1}
$$

## Rekursive Implementierung

In [11]:
class binomialkoeffizient:
  def __init__(self, n, k):
    self.n = n
    self.k = k
    self.count = 0
    self.bin = self.__binomialkoeffizient(self.n, self.k)

  def __str__(self):
    return f"Binomialkoeffizient ({self.n} {self.k}) = {self.bin} [rekursioncount: {self.count:_}]"

  def __binomialkoeffizient(self, n, k):
    self.count += 1
    # ------------ Basisfälle
    if n == k:
      return 1
    if k == 0:
      return 1
    # ------------ Rekursion
    return self.__binomialkoeffizient(n-1, k) + self.__binomialkoeffizient(n-1, k-1)

print(binomialkoeffizient(4, 2))
print(binomialkoeffizient(49, 6))

Binomialkoeffizient (4 2) = 6 [rekursioncount: 11]
Binomialkoeffizient (49 6) = 13983816 [rekursioncount: 27_967_631]


## Dynamische Programmierung

### Mit Rekursion

In [25]:
class binomialkoeffizient:
  def __init__(self, n, k):
    self.n = n
    self.k = k
    self.count = 0
    self.bin_dict = {}
    self.bin = self.__binomialkoeffizient(self.n, self.k)

  def __str__(self):
    return f"Binomialkoeffizient ({self.n} {self.k}) = {self.bin:_} [rekursioncount: {self.count:_}]"
  
  def __binomialkoeffizient(self, n, k):
    self.count += 1
    # ------------ Basisfälle
    if n == k:
      self.bin_dict[(n, k)] = 1
      return self.bin_dict[(n, k)]
    if k == 0:
      self.bin_dict[(n, k)] = 1
      return self.bin_dict[(n, k)]

    # ------------ Rekursion
    if (n, k) in self.bin_dict:
      return self.bin_dict[(n, k)]
    else:
      self.bin_dict[(n, k)] = self.__binomialkoeffizient(n-1, k) + self.__binomialkoeffizient(n-1, k-1)
      return self.bin_dict[(n, k)]

print(binomialkoeffizient(4, 2))
print(binomialkoeffizient(49, 6))

Binomialkoeffizient (4 2) = 6 [rekursioncount: 9]
Binomialkoeffizient (49 6) = 13_983_816 [rekursioncount: 517]


In dieser Implementierung wird weiterhin eine Rekursion verwendet um die Teilergebnisse zu berechnen. Allerdings wird eine Art Cache verwendet um die Teilergebnisse zu speichern. Dieser wird in der folgenden Zeile abgefragt und weiter befüllt:

```python
if (n, k) in self.bin_dict:
  return self.bin_dict[(n, k)]
else:
  self.bin_dict[(n, k)] = self.__binomialkoeffizient(n-1, k) + self.__binomialkoeffizient(n-1, k-1)
    return self.bin_dict[(n, k)]
```

Dadurch ergibt sich jedoch auch eine verbesserte Laufzeit, da die Teilergebnisse nicht mehr mehrfach berechnet werden müssen. Die Laufzeit beträgt O(n*k) und der Speicherbedarf O(n*k).

### Mit Iterativer Konstruktion

In [ ]:
import numpy as np

class binomialkoeffizient:
  def __init__(self, n, k):
    self.n = n
    self.k = k
    self.count = 0
    self.bin_arr = np.zeros((n+1, n+1)) # n x n großes Array erstellen
    #self.bin = self.__binomialkoeffizient(self.n, self.k)
    self.__binomialkoeffizient(self.n, self.k)

  def __str__(self):
    return f"Binomialkoeffizient ({self.n} {self.k}) = {1} [rekursioncount: {self.count:_}]"
  
  def str_array(self):
    return f"{self.bin_arr}"
  
  def __binomialkoeffizient(self, n, k):
    self.count += 1
    # ------------ Basisfälle
    for i in range(0, n+1):
      self.bin_arr[i][i] = 1

    for i in range(0, n+1):
      self.bin_arr[i][0] = 1
  
    i = 2
    j = 1

    while i <= n:

      while j < i:
        self.bin_arr[i][j] = self.bin_arr[i-1][j] + self.bin_arr[i-1][j-1]
        j += 1

      i += 1
      j = 1   # das ist leider so in python

bin_1 = binomialkoeffizient(4, 2)
print(bin_1.str_array())

bin_2 = binomialkoeffizient(5, 3)
print(bin_2.str_array())

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [1. 3. 3. 1. 0.]
 [1. 4. 6. 4. 1.]]
[[ 1.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.]
 [ 1.  3.  3.  1.  0.  0.]
 [ 1.  4.  6.  4.  1.  0.]
 [ 1.  5. 10. 10.  5.  1.]]
