# Aufgabe einer Probeklausur (Längste gemeinsame Teilfolge)

In [18]:
import numpy as np

def dyn_sequence(a:list[int], b:list[int]):
  m = len(a) + 1
  n = len(b)

  C = np.zeros((m, n))
  print(C)

  for i in range(1, m):
    el = a[i - 1]
    found = False
    for j in range(0, n):
      if found:
        C[i][j] = C[i][j - 1]
        continue
      if b[j] == el:
        C[i][j] = C[i - 1][j] + 1
        found = True
      else:
        C[i][j] = C[i - 1][j]
    #print(C)
  
  print(C)

#a = [10, 4, 20, 10, 40, 2, 0, 60]
#b = [4, 90, 7, 10, 70, 2, 71, 81, 0]
#a = [3, 9, 8, 3, 9, 7, 9, 7, 0, 6, 2, 1]
#b = [9, 3, 7, 9, 2, 1, 0, 8, 6, 2]
#a = [1, 1, 1, 1, 1, 1, 1]
#b = [1, 1, 1, 1, 1, 1, 1]
#a = [1, 0, 0, 0, 0, 0, 0]
#b = [1, 1, 1, 1, 1, 1, 1]
a = [1, 0, 1, 0, 1, 0, 1]
b = [1, 0, 1, 0, 1, 0, 1]

dyn_sequence(a, b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2.]
 [2. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3.]
 [3. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4.]]


In [ ]:
import numpy as np

def dyn_sequence(a:list[int], b:list[int]):
  m = len(a) + 1
  n = len(b)

  C = np.zeros((m, n))
  print(C)

  for i in range(1, m):
    el = a[i - 1]
    found = False
    for j in range(0, n):
      if found:
        C[i][j] = C[i][j - 1]
        continue
      if b[j] == el:
        C[i][j] = C[i - 1][j - 1] + 1
        found = True
      else:
        C[i][j] = C[i - 1][j - 1]
    #print(C)
  
  print(C)

a = [10, 4, 20, 10, 40, 2, 0, 60]
b = [4, 90, 7, 10, 70, 2, 71, 81, 0]
#a = [3, 9, 8, 3, 9, 7, 9, 7, 0, 6, 2, 1]
#b = [9, 3, 7, 9, 2, 1, 0, 8, 6, 2]
#a = [1, 1, 1, 1, 1, 1, 1]
#b = [1, 1, 1, 1, 1, 1, 1]
#a = [1, 0, 0, 0, 0, 0, 0]
#b = [1, 1, 1, 1, 1, 1, 1]
#a = [1, 0, 1, 0, 1, 0, 1]
#b = [1, 0, 1, 0, 1, 0, 1]

dyn_sequence(a, b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 6. 6. 7. 7. 7. 8. 8. 8. 8.]
 [8. 7. 6. 6. 7. 7. 7. 8. 9. 9.]
 [9. 8. 7. 6. 7. 7. 7. 7. 7. 7.]
 [7. 9. 8. 7. 6. 8. 8. 8. 8. 8.]]
