# Zahlendreieck

In [17]:
import numpy as np

def zahlenDreieck(a: list[list[int]]):
  print(a)
  arrdim = len(a)
  print(arrdim)
  s = np.zeros((arrdim, arrdim), dtype=int)
  print(s)
  # Basisfall 1
  s[0][0] = a[0][0]

  for i in range(1, arrdim):
    for j in range(0, i + 1):
      # Basisfall 2 (ganze linke Spalte)
      if j == 0:
        s[i][j] = a[i][j] + s[i - 1][j]
      else:
        s[i][j] = max(a[i][j] + s[i - 1][j], a[i][j] + s[i - 1][j - 1])

  print(s)
  maxval = 0
  for j in range(0, arrdim):
    curr = s[arrdim - 1][j]
    if curr > maxval:
      maxval = curr
  
  return maxval

board = np.asarray([
  [10, -1, -1, -1, -1, -1, -1],
  [82, 81, -1, -1, -1, -1, -1],
  [4 ,  6, 10, -1, -1, -1, -1],
  [2 , 14, 35,  7, -1, -1, -1],
  [41,  3, 52, 26, 15, -1, -1],
  [32, 90, 11, 87, 56, 23, -1],
  [54, 65, 89, 32, 71,  9, 31],
])

retval = zahlenDreieck(board)
print(retval)

[[10 -1 -1 -1 -1 -1 -1]
 [82 81 -1 -1 -1 -1 -1]
 [ 4  6 10 -1 -1 -1 -1]
 [ 2 14 35  7 -1 -1 -1]
 [41  3 52 26 15 -1 -1]
 [32 90 11 87 56 23 -1]
 [54 65 89 32 71  9 31]]
7
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[ 10   0   0   0   0   0   0]
 [ 92  91   0   0   0   0   0]
 [ 96  98 101   0   0   0   0]
 [ 98 112 136 108   0   0   0]
 [139 115 188 162 123   0   0]
 [171 229 199 275 218 146   0]
 [225 294 318 307 346 227 177]]
346
