# Zuschnittsproblem

In [28]:
import numpy as np

def dynCutting(w:list):
  print(w)

  n = len(w)

  G = np.zeros((n, n))
  print(G)

  i = 1
  while i <= (n - 1):
    x = 1
    while x <= (n - 1):
      # Übernehme den ursprünglichen Wert der vorherigen Iteration für die aktuelle Länge x
      G[i][x] = G[i - 1][x]

      # Prüfe ob die derzeit zulässige Länge x ausreicht, um ein Stück der aktuellen Länge (i) zu nutzen
      if x - i >= 0:
        t = w[i] + G[i - 1][x - i]
        p = G[i][x]
        G[i][x] = max(p, t)

      x += 1
    i += 1

  print(G)
  x -= 1
  i -= 1

  # Ermittle Rückwerts welche Teile ermittelt wurden
  parts = []
  while i >= 0:
    curr = G[i][x]
    above = G[i - 1][x]
    # Wenn eine Wertänderung zum vorherigen Sichtbar ist nehme das Teil
    if curr != above:
      parts.append(i)
      x = x - i
    i -= 1

  return(parts)


rewards = [0, 2, 3, 8, 9]

parts = dynCutting(rewards)

rew = 0
for el in parts:
  rew += rewards[el]

print(f"Parts: {parts} Reward: {rew}€")


[0, 2, 3, 8, 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  2.  2.  2.  2.]
 [ 0.  2.  3.  5.  5.]
 [ 0.  2.  3.  8. 10.]
 [ 0.  2.  3.  8. 10.]]
Parts: [3, 1] Reward: 10€


In [ ]:
import numpy as np

def dynCutting(w:list):
  print(w)

  n = len(w)

  G = np.zeros((n, n))
  print(G)

  i = 1
  while i <= (n - 1):
    x = 1
    while x <= (n - 1):
      # Übernehme den ursprünglichen Wert der vorherigen Iteration für die aktuelle Länge x
      G[i][x] = G[i - 1][x]

      # Prüfe ob die derzeit zulässige Länge x ausreicht, um ein Stück der aktuellen Länge (i) zu nutzen
      if x - i >= 0:
        t = w[i] + G[i - 1][x - i]
        # Prüfe ob ein das vorherige ein zweites mal passen würde
        p = G[i][x]
        if x - (i - 1) >= 0:
          p = p + p
        G[i][x] = max(p, t)

      x += 1
    i += 1

  print(G)
  x -= 1
  i -= 1

  # Ermittle Rückwerts welche Teile ermittelt wurden
  parts = []
  while i >= 0:
    curr = G[i][x]
    above = G[i - 1][x]
    # Wenn eine Wertänderung zum vorherigen Sichtbar ist nehme das Teil
    if curr != above:
      parts.append(i)
      x = x - i
    i -= 1

  return(parts)


rewards = [0, 2, 3, 8, 9]

parts = dynCutting(rewards)

rew = 0
for el in parts:
  rew += rewards[el]

print(f"Parts: {parts} Reward: {rew}€")
